### PR TITLE
Added a fuzzer for initial integration with OSS-Fuzz.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Hi Maintainers,

I have worked a bit on setting fuzzing up for gpac by way of OSS-Fuzz. Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects, and it would be great to have gpac integrated. The only expectation of integrating into OSS-Fuzz is that bugs will be fixed. This is not a "hard" requirement in that no one enforces this and the main point is if bugs are not fixed then it is a waste of resources to run the fuzzers, which we would like to avoid.

In this PR https://github.com/google/oss-fuzz/pull/5289 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate gpac. If you would like to integrate, could you please provide a set of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. The emails should be linked to a Google account in order to view the detailed reports and notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

At the moment I stored the fuzzers in the Google OSS-Fuzz repository, but we can move them up here to make maintenance easier.

### CODE REVIEW

**Comment by rbouqueau** [comment]
Hi David, many thanks for bootstrapping this.

@jeanlf @aureliendavid @cconcolato  Wouldn't it be an opportunity to consolidate the work started years ago with AFL?

**Comment by jeanlf** [comment]
Thanks indeed.
FYI, we already run fuzzing on gpac in our CI platform, results here: https://tests.gpac.io/testres/fuzzing, but we don't yet have a public interface for submitting new fuzzing tests.

**Comment by DavidKorczynski** [comment]
> Thanks indeed.
> FYI, we already run fuzzing on gpac in our CI platform, results here: https://tests.gpac.io/testres/fuzzing, but we don't yet have a public interface for submitting new fuzzing tests.

Ah that's great. I think OSS-Fuzz probably brings a fair amount of more features, amongst other things coverage, crash analysis and more. It also comes with a nice UI where you can browse all bugs and statistics. OSS-Fuzz also comes with continuous fuzzing and we can integrate it such that the fuzzers will be part of the CI as well, namely that the fuzzers is run for each new PR to the project.

**Comment by aureliendavid** [comment]
This is interesting. I haven't had time to look into it in details yet.

If you have more info or documentation on what we would need to do on the gpac side to integrate with it, I'll take a look when I can. 

Thanks.

**Comment by DavidKorczynski** [comment]
> This is interesting. I haven't had time to look into it in details yet.
> 
> If you have more info or documentation on what we would need to do on the gpac side to integrate with it, I'll take a look when I can.
> 
> Thanks.

Essentially the only thing that is needed for getting this up and running is a set of emails that will receive notifications with bug reports (this is described in the first message of this PR). Then when this is merged in we can merge things on the OSS-Fuzz side and the fuzzer will start being run.

**Comment by aureliendavid** [comment]
I've only ever used afl+asan so I'll need to look into libfuzzer (that's what is used by oss-fuzz right?) to see how to add fuzzers and things like that.

Is storing fuzzers on the main repo mandatory? Because I think for us it would make more sense to store them in our tests repo (https://github.com/gpac/testsuite). 

Other than that I think it would be good to use this for gpac.

**Comment by DavidKorczynski** [comment]
> 
> Is storing fuzzers on the main repo mandatory? Because I think for us it would make more sense to store them in our tests repo (https://github.com/gpac/testsuite).
> 
> Other than that I think it would be good to use this for gpac.

We can place the fuzzers anywhere. I can upload it to the testsuite repository or we can also start with keeping the fuzzers in the OSS-Fuzz repository - it's up to you! Let me know which you prefer and I will fix it up.

**Comment by aureliendavid** [comment]
> we can also start with keeping the fuzzers in the OSS-Fuzz repository

ok I think it would make sense to start like this (with the fuzzers in the oss-fuzz repo) while we get familiar with the tools

as for a maintainer email address, we can use: project.gpac@gmail.com

**Comment by aureliendavid** [comment]
oss-fuzz is now up and running for gpac so I'll close this, thanks @DavidKorczynski for the integration

next steps will be: 
 - fix issues found by oss-fuzz
 - add more fuzzers for more coverage
 - move fuzzers from oss-fuzz repo to our testsuite (or other?)

**Comment by DavidKorczynski** [comment]
> oss-fuzz is now up and running for gpac so I'll close this, thanks @DavidKorczynski for the integration

My pleasure! 

> next steps will be:
> 
> * move fuzzers from oss-fuzz repo to our testsuite (or other?)

I can help with this one if you tell me where you would like to have the fuzzers placed. Should we put it in a `/fuzz` folder to start?

**Comment by aureliendavid** [comment]
> I can help with this one if you tell me where you would like to have the fuzzers placed. Should we put it in a `/fuzz` folder to start?

thanks, I think we need to decide on a location first 

I'd say the choice is between: 
1. a `/oss-fuzzers` directory in the https://github.com/gpac/testsuite repo
2. or a new `oss-fuzzers` repo under https://github.com/gpac

probably 1. makes more sense now and 2. if it gets larger

**Pull request closed without merging**
