### PR TITLE
rudimentary mfra/tfra support

### PR DESCRIPTION
**Pull request by porcelijn**
Hi!

I made some changes in order to read and dump fragment random access boxes. This is useful for debugging timelines (ie compare random access to moof/trun/sample timestamps); see example below. If you find this useful, please merge into main branch.

Cheers, Tijn

```xml
...
  <MovieFragmentRandomAccessBox>
    <BoxInfo Size="124" Type="mfra"/>
    <TrackFragmentRandomAccessBox TrackId="1" number_of_entries="4">
      <BoxInfo Size="100" Type="tfra"/>
      <RandomAccessEntry time="713644175737" moof_offset="657" traf="1" trun="1" sample="1"/>
      <RandomAccessEntry time="713664377098" moof_offset="17051" traf="1" trun="1" sample="1"/>
      <RandomAccessEntry time="713684346259" moof_offset="33248" traf="1" trun="1" sample="1"/>
      <RandomAccessEntry time="713704315420" moof_offset="49445" traf="1" trun="1" sample="1"/>
    </TrackFragmentRandomAccessBox>
    <UnknownBox>
      <BoxInfo Size="16" Type="mfro"/>
    </UnknownBox>
  </MovieFragmentRandomAccessBox>
</IsoMediaFile>
```

### CODE REVIEW

**Comment by porcelijn** [comment]
Please consider changset https://github.com/gpac/gpac/commit/8568015ff771768b566554e9720a1f9909865f87 instead - my earlier earlier request was full of errors.

**Comment by rbouqueau** [comment]
Ok for me. Others?

**Comment by jeanlf** [comment]
OK merged, thanks !

**Comment by porcelijn** [comment]
Thanks!

**Pull request merged**
