### PR TITLE
Fix shift exponent is too large in gf_bs_write_int

### PR DESCRIPTION
**Pull request by stanionascu**
When importing mp4's containing dvcc box, MP4Box will fail complaining that:
`utils/bitstream.c:552:9: runtime error: shift exponent 4294967168 is too large for 32-bit type 'unsigned int'`

It was hapenning due to 160 being passed into the `gf_bs_write_int` (from dvcc_Write) and shifting the value beyond the valid range.

The fix ensures that the value is correctly written, by draining the count of bits all the way up until it reaches an acceptable value.

### CODE REVIEW

**Comment by stanionascu** [comment]
Can anyone have a look at this ?

**Comment by rbouqueau** [comment]
Yes we will :)
Thanks for reporting and sorry for the delays.

**Comment by rbouqueau** [comment]
LGTM. @jeanlf Should we add a log message in this case?

**Comment by jeanlf** [comment]
Looks good, but I think we should rather throw throw an error if nBits is greater than 32, since gf_bs_write_long_int should be used instead. Note that dvcC in filters does not use have this issue.

**Comment by rbouqueau** [comment]
By "throw an error" you mean ```GF_LOG(GF_LOG_ERROR, ...```, correct?

**Comment by jeanlf** [comment]
yes

**Comment by rbouqueau** [comment]
@stanionascu Can you add it, or should I duplicate your branch to add commits?

**Comment by stanionascu** [comment]
@rbouqueau sure I can amend the commit.

**Comment by stanionascu** [comment]
@rbouqueau @jeanlf  
> Looks good, but I think we should rather throw throw an error if nBits is greater than 32, since gf_bs_write_long_int should be used instead. Note that dvcC in filters does not use have this issue.
> @stanionascu Can you add it, or should I duplicate your branch to add commits?

i've pushed latest changes:
* error logging and draining to both `gf_bs_write_*_int` methods.
* use `gf_bs_write_data` in `dvcC_Write` as symmetric to `gf_bs_read_data` in `dvcC_Read`

**Comment by rbouqueau** [comment]
LGTM

@Jean please merge if ok for you

**Comment by rbouqueau** [comment]
@stanionascu Many thanks :)

**Comment by jeanlf** [comment]
thanks!

**Pull request merged**
