### PR TITLE
Removing duplicates in fileimport.c in MP4Box

### PR DESCRIPTION
**Pull request by RodolpheFouquet**
- the duplicate doesn't exist on the filters branch, which served as a guideline for this fix
- some errors could be overwritten, they are now managed.

### CODE REVIEW

**Comment by jeanlf** [comment]
you need to patch the following functions as well:
```
gf_import_timed_text
gf_import_raw_unit
```
These functions currently don't set the number of tracks on import probing, your patch will break these importers

**Comment by RodolpheFouquet** [comment]
Hey, thanks, I'll fix that then.

**Comment by RodolpheFouquet** [comment]
Is it possible to have command line examples so I can try before & after the patch and verify I'm not breaking that specific nb_track == 0 case?

**Comment by rbouqueau** [comment]
Jean tells me it is about chapters.

I can see the coverage in https://tests.gpac.io/testres/lcov/1644. It seems like it is more about languages (as szLan) is non-null but I couldn't extract the proper test. Idea anyone?

**Comment by RodolpheFouquet** [comment]
Well, about the tests, the same number of tests are passing before and after my PR (when I run the tests).

**Comment by rbouqueau** [comment]
Since this only affects master, I merge.

**Pull request merged**
