### PR TITLE
Fix disable flag build

### PR DESCRIPTION
**Pull request by canatella**
To reduce the size of my Android builds, I'm using the various GPAC_DISABLE_* flags, but for some of those, it breaks the build.

### CODE REVIEW

**Comment by jeanlf** [comment]
could you give me the complete list of flags you disable ?

**Comment by canatella** [comment]
"GPAC_DISABLE_SVG",
        "GPAC_DISABLE_SCENEGRAPH",
        "GPAC_DISABLE_X3D",
        "GPAC_MINIMAL_ODF",
        "GPAC_DISABLE_BIFS",
        "GPAC_DISABLE_LASER",
        "GPAC_DISABLE_SAF",
        "GPAC_DISABLE_SENG",
        "GPAC_DISABLE_QTVR",
        "GPAC_DISABLE_AVILIB",
        "GPAC_DISABLE_OGG",
        "GPAC_DISABLE_MEDIA_EXPORT",
        "GPAC_DISABLE_SWF_IMPORT",
        "GPAC_DISABLE_SCENE_STATS",
        "GPAC_DISABLE_SCENE_DUMP",
        "GPAC_DISABLE_LOADER_ISOM",
        "GPAC_DISABLE_LOADER_BT",
        "GPAC_DISABLE_LOADER_XMT",
        "GPAC_DISABLE_MCRYPT",
        "GPAC_DISABLE_ISOM",
        "GPAC_DISABLE_ISOM_WRITE",
        "GPAC_DISABLE_OD_DUMP",
        "GPAC_DISABLE_ISOM_DUMP",
        "GPAC_DISABLE_STREAMING",
        "GPAC_DISABLE_TTXT",
        "GPAC_DISABLE_TTML",
        "GPAC_DISABLE_VOBSUB",
        "GPAC_DISABLE_VTT",
        "GPAC_DISABLE_VALIDATOR",

**Comment by jeanlf** [comment]
could you heck if the compilation is now fine ?

**Comment by canatella** [comment]
Yes it does compile correctly, thanks!

**Pull request closed without merging**
