### PR TITLE
gf_isom_get_edit_list_type() offset is consistently in media timescale

### PR DESCRIPTION
**Pull request by rbouqueau**
@jeanlf used at https://github.com/gpac/gpac/search?utf8=%E2%9C%93&q=gf_isom_get_edit_list_type&type= so seems ok to me. Please merge if ok for you too

### CODE REVIEW

**Comment by jeanlf** [comment]
actually no, mediaOffset is in media timescale, here you  move it to movie timescale

**Comment by rbouqueau** [comment]
@jeanlf I don't agree since we divide by ```moov->mvhd->timeScale``` and multiply by ```Media->mediaHeader->timeScale```.

The PR is here to make sure that there is no additional side effect to fixing this (see https://github.com/gpac/gpac/search?utf8=%E2%9C%93&q=gf_isom_get_edit_list_type&type= for calls to this function).

Please merge is ok, contact me if not!

**Comment by jeanlf** [comment]
typed too fast - what I meant is that ent->mediaTime is already in media timescale, not in movie timescale as your patch seems to assume

**Comment by rbouqueau** [comment]
got it! see c92e298be3

**Pull request closed without merging**
