### PR TITLE
uncompressed: add icbr and cmpC box dump

### PR DESCRIPTION
**Pull request by bradh**
From 23001-17 draft AMD2.

Also includes some minor typo fixes I noted while reading. I'll split those out if you'd prefer.

### CODE REVIEW

**Comment by bradh** [comment]
Some sample files.
[rgb_generic_compressed_samples.zip](https://github.com/user-attachments/files/16117548/rgb_generic_compressed_samples.zip)

**Comment by jeanlf** [comment]
Could you split the typo fixes in a seperate PR ? We'll wait for AMD2 to be frozen before adding support for these boxes.

**Comment by bradh** [comment]
Typos now in #2913. Will convert this to a draft and update as required.

**Comment by bradh** [comment]
I think AMD 2 has progressed enough to add this.

Have updated the implementation to match the DAM, except for `cmpC` where I omitted the `must_decompress_individual_units`.

I am unsure what is the best way to handle the implied offset (i.e. where `unit_offset_nbbits` is 0). In this implementation, I have tracked the implied offsets, and included them as if they were present. However it might also be possible to just not show the offset. Review feedback appreciated.

**Comment by jeanlf** [comment]
> Have updated the implementation to match the DAM, except for cmpC where I omitted the must_decompress_individual_units.

I think we should dump it as it is still present in the AMD2 text

> However it might also be possible to just not show the offset. 

I'd rather go for this, and only dump offsets when present in the box.

Can you update the PR to reflect these?

**Comment by bradh** [comment]
> > Have updated the implementation to match the DAM, except for cmpC where I omitted the must_decompress_individual_units.
> 
> I think we should dump it as it is still present in the AMD2 text

I have made this change, although I could see it both ways.
 
> I'd rather go for this, and only dump offsets when present in the box.

Fixed.

**Comment by jeanlf** [comment]
Thanks !

**Pull request merged**
