### PR TITLE
Rfc 6381 size

### PR DESCRIPTION
**Pull request by rbouqueau**

### CODE REVIEW

**Comment by rbouqueau** [comment]
Please merge when ok for you :)

**Comment by jeanlf** [comment]
any reason why using 40 bytes max to store the codecs param ? This might be a bit short for LHVC content

**Comment by rbouqueau** [comment]
Arbitrary value that looked sufficient to me. Which max would you prefer?

I could also store the max size in a central place. Which one? constants.h?

**Comment by jeanlf** [comment]
yes, using a define in constant.h seems right

**Comment by rbouqueau** [comment]
Which value >40?

**Comment by jeanlf** [comment]
you can put 80 or 100 should be enough for now

**Comment by rbouqueau** [comment]
better now? :)

**Comment by jeanlf** [comment]
perfect, merged !

**Pull request merged**
