### PR TITLE
dasher shouldn't anticipate segment boundary on video

### PR DESCRIPTION
**Pull request by rbouqueau**
There are 3 distincts commits in this PR that could be cherry-picked if the PR is not acceptable.

### CODE REVIEW

**Comment by aureliendavid** [comment]
Hi, 

one small thing: when branch names contains underscores (and probably other characters) it trips the debian packaging script and the buildbot process fails for the linux workers 

> dh_strip: warning:     debian/changelog(l1): version '2.5-DEV-rev506-g6da37dcc-buildbot-reframer_sap' is invalid: version number contains illegal character '_'

we should probably add a fix to this but in the meantime for buildbot-* branches it's better to stick to alphanum + dashes


other than that, if we look at the tests that did run (https://tests.gpac.io/revision/2.5-DEV-rev506-g6da37dcc-buildbot-reframer_sap and check "Hide lines with any OK") it looks like the tests for: 

* add-subsamples-HEVC
* shvc
* svc

result in a different hashes than on master. 

It might be intended that the correct result for these tests has changed with this PR, in which case a PR in the testsuite repo with the new correct hashes would be appreciated. 

Or it might be a bug in the PR that can be fixed here.

**Comment by rbouqueau** [comment]
@aureliendavid Thank you. Indeed the hashes changed.

Waiting for @jeanlf 's feedback.

**Comment by jeanlf** [comment]
OK with the first two commits, but I'm not sure what you're trying to fix on the dasher. Would you have a sample faulty stream ?

**Comment by rbouqueau** [comment]
```
$ gpac -i https://dash-large-files.akamaized.net/dvb-ibc-2024/13%20-%205G%20Broadcast%20Booth%20Version.mp4 c=avc:fintra=2:FID=V1 -o dash.mpd:SID=V1:profile=dashavc264.live:segdur=2
No filter chain found for PID A2 in filter mp4dmx to any loaded filters - NOT CONNECTED
[Dasher] WARNING! Max SAP type 3 detected - switching to FULL profile
```

We detect SAP type 3 because GPAC switches too early (ie not on the `fintra` SAP1).

**Comment by jeanlf** [comment]
OK I think this is correct, the patch is indeed mostly for audio but should not apply to video. Maybe we'll need a way to configure this through an option in case we encounter audio encodings that include the initial priming duration in the first SAP period.

**Pull request merged**
